# kind: Namespace
# apiVersion: v1
# metadata:
#   name: kong
# ---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: kong-template
  namespace: kong
parameters:
  - name: postgres_password
    description: Password for the PostgreSQL database
    required: true
  - name: postgres_user
    description: Username for the PostgreSQL database
    required: true
  - name: postgres_database
    description: Name for the PostgreSQL database
    required: true    
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: kong-config
      namespace: kong
    data:
      KONG_NGINX_DAEMON: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: kong-postgres-pvc
      namespace: kong
      finalizers:
          - kubernetes.io/pvc-protection
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
    status:
      phase: Bound
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 5Gi
  - kind: Secret
    apiVersion: v1    
    metadata:
      name: kong-database-secret
      namespace: kong
    type: Opaque
    data:
      postgres_password: ${postgres_password}
      postgres_user: ${postgres_password}
      postgres_database: ${postgres_database}
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      # annotations:
      #   template.alpha.openshift.io/wait-for-ready: "true"
      name: kong-database
      namespace: kong
    spec:
      replicas: 1
      selector:
        app: kong-database
      strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: kong-database
        spec:
          containers:
            - name: kong-database
              image: postgresql
              ports:
                - containerPort: 5432
                  protocol: TCP
              env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: kong-database-secret
                      key: postgres_user
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: kong-database-secret
                      key: postgres_password
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: kong-database-secret
                      key: postgres_database
              securityContext:
                capabilities: {}
                privileged: false
              volumeMounts:
                - mountPath: /var/lib/pgsql/data
                  name: kong-postgres-data
          volumes:
            - name: kong-postgres-data
              persistentVolumeClaim:
                claimName: kong-postgres-pvc
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - kong-database
            from:
              kind: ImageStreamTag
              name: postgresql:10-el8
              namespace: openshift
          type: ImageChange
        - type: ConfigChange
  - kind: Service
    apiVersion: v1
    metadata:
      name: kong-database
      namespace: kong
    spec:
      selector:
        app: kong-database
      ports:
        - name: postgres
          port: 5432
          targetPort: 5432
  - kind: Service
    apiVersion: v1
    metadata:
      name: kong-database-nodeport
      namespace: kong
    spec:
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - nodePort: 30984
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        app: kong-database
      sessionAffinity: None
      type: NodePort
  - kind: Job
    apiVersion: batch/v1
    metadata:
      name: kong-migration
      namespace: kong
    spec:
      template:
        metadata:
          name: kong-migration
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kong-migration
              image: kong:latest
              imagePullPolicy: IfNotPresent
              command: ["kong", "migrations", "bootstrap"]
              env:
                - name: KONG_DATABASE
                  value: postgres
                - name: KONG_PG_HOST
                  value: kong-database
                - name: KONG_PG_USER
                  valueFrom:
                    secretKeyRef:
                      name: kong-database-secret
                      key: postgres_user
                - name: KONG_PG_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: kong-database-secret
                      key: postgres_password
                - name: KONG_PROXY_ACCESS_LOG
                  value: /dev/stdout
                - name: KONG_ADMIN_ACCESS_LOG
                  value: /dev/stdout
                - name: KONG_PROXY_ERROR_LOG
                  value: /dev/stderr
                - name: KONG_ADMIN_ERROR_LOG
                  value: /dev/stderr
  - kind: Service
    apiVersion: v1
    metadata:
      name: kong-proxy
      namespace: kong
    spec:
      selector:
        app: kong-proxy
      ports:
        - name: api
          port: 8000
          targetPort: 8000
        - name: admin
          port: 8001
          targetPort: 8001
        # - name: manager
        #   port: 8002
        #   targetPort: 8002
        # - name: portal
        #   port: 8003
        #   targetPort: 8003
        # - name: portal-files
        #   port: 8004
        #   targetPort: 8004
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: kong-proxy
      namespace: kong
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      replicas: 1
      selector:
        app: kong-proxy
      template:
        metadata:
          labels:
            app: kong-proxy
        spec:
          containers:
            - name: kong-proxy
              # dependsOn:
              # - name: kong-migration
              #   condition: Complete
              image: kong:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: KONG_DATABASE
                  value: postgres
                - name: KONG_PG_HOST
                  value: kong-database
                - name: KONG_PG_USER
                  valueFrom:
                    secretKeyRef:
                      name: kong-database-secret
                      key: postgres_user
                - name: KONG_PG_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: kong-database-secret
                      key: postgres_password
                - name: KONG_PROXY_ACCESS_LOG
                  value: /dev/stdout
                - name: KONG_ADMIN_ACCESS_LOG
                  value: /dev/stdout
                - name: KONG_PROXY_ERROR_LOG
                  value: /dev/stderr
                - name: KONG_ADMIN_ERROR_LOG
                  value: /dev/stderr
                - name: KONG_LOG_LEVEL
                  value: info
                - name: KONG_ADMIN_LISTEN
                  value: 0.0.0.0:8001
                # - name: KONG_PORTAL
                #   value: "on"
              ports:
                - containerPort: 8000
                - containerPort: 8001
                # - containerPort: 8002
                # - containerPort: 8003
                # - containerPort: 8004
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: api
      namespace: kong
    spec:
      host: api-kong.apps-crc.testing
      to:
        kind: Service
        name: kong-proxy
        weight: 100
      port:
        targetPort: api
      wildcardPolicy: None
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: admin
      namespace: kong
    spec:
      host: admin-kong.apps-crc.testing
      to:
        kind: Service
        name: kong-proxy
        weight: 100
      port:
        targetPort: admin
      wildcardPolicy: None

  # - apiVersion: route.openshift.io/v1
  #   kind: Route
  #   metadata:
  #     name: manager
  #     namespace: kong
  #   spec:
  #     host: manager-kong.apps-crc.testing
  #     to:
  #       kind: Service
  #       name: kong-proxy
  #       weight: 100
  #     port:
  #       targetPort: manager
  #     wildcardPolicy: None

  # - apiVersion: route.openshift.io/v1
  #   kind: Route
  #   metadata:
  #     name: portal
  #     namespace: kong
  #   spec:
  #     host: portal-kong.apps-crc.testing
  #     to:
  #       kind: Service
  #       name: kong-proxy
  #       weight: 100
  #     port:
  #       targetPort: portal
  #     wildcardPolicy: None